debug: true
info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"
spring:
  cloud:
    deployer:
      local:
        free-disk-space-percentage: 0
#    dataflow:
#      security:
#        authorization:
#          map-oauth-scopes: true

logging:
  config: classpath:logback-scdf-local.xml

#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-alias: dataflow
#    key-store: "/your/path/to/dataflow.keystore"
#    key-store-type: jks
#    key-store-password: dataflow
#    key-password: dataflow

# Oauth 2 support:

#security:
#  oauth2:
#    client:
#      client-id: myclient
#      client-secret: mysecret
#      access-token-uri: http://127.0.0.1:9999/oauth/token
#      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize
#    resource:
#      user-info-uri: http://127.0.0.1:9999/me

# UAA Security

#security:
#  oauth2:
#    client:
#      client-id: app
#      client-secret: dataflow
#      access-token-uri: http://dataflow.local:8080/uaa/oauth/token
#      user-authorization-uri: http://dataflow.local:8080/uaa/oauth/authorize
#    resource:
#      user-info-uri: http://dataflow.local:8080/uaa/userinfo

# If you prefer to use Eureka to locate the Config Server, you can do that by setting
# spring.cloud.config.discovery.enabled=true (default "false"). The net result of that is
# that client apps all need a bootstrap.yml (or an environment variable) with the Eureka
# server address, e.g. in eureka.client.serviceUrl.defaultZone
#
#---
#spring:
#  cloud:
#     config:
#        discovery:
#           enabled: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
