apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    app: kafka-broker
    component: kafka-broker
spec:
  ports:
  - port: 9092
    name: kafka-broker-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-broker
    component: kafka-broker-c
