(@ load("@ytt:data", "data") @)#@data/values
---
scdf:
  deploy:
    binder:
      type: rabbit
    database:
      type: mariadb
  server:
    image:
      repository: (@= data.values.server.repository @)
      tag: (@= data.values.server.version @)
  ctr:
    image:
      tag: (@= data.values.ctr.version @)
  skipper:
    image:
      tag: (@= data.values.skipper.version @)
  feature:
    monitoring:
      grafana:
        enabled: true
        image:
          tag: (@= data.values.grafana.version @)
      prometheus:
        enabled: true
      prometheusRsocketProxy:
        enabled: true
