#@data/values
---
scdf:
  deploy:
    database:
      type: mysql
  server:
    image:
      tag: 2.9.5-SNAPSHOT
    service:
      type:
        NodePort
  skipper:
    image:
      tag: 2.8.5-SNAPSHOT
  ctr:
    image:
      tag: 2.9.5-SNAPSHOT
