(@ load("@ytt:data", "data") @)#@data/values
---
scdf:
  server:
    image:
      repository: (@= data.values.server.repository @)
      tag: (@= data.values.server.version @)
  ctr:
    image:
      tag: (@= data.values.ctr.version @)
  skipper:
    image:
      tag: (@= data.values.skipper.version @)
  feature:
    monitoring:
      grafana:
        image:
          tag: (@= data.values.grafana.version @)
  binder:
    type: rabbit
    rabbit:
      host: (@= data.values.scdf.binder.rabbit.host @)
      port: (@= data.values.scdf.binder.rabbit.port @)
      username: (@= data.values.scdf.binder.rabbit.username @)
      password: (@= data.values.scdf.binder.rabbit.password @)
