version: '3'

services:
  dataflow-server:
    environment:
      - |
        SPRING_APPLICATION_JSON=
        {
          "spring.cloud.skipper.client.serverUri":"http://skipper-server:7577/api",
          "spring.cloud.dataflow.applicationProperties":{
             "stream.spring.cloud.stream.kafka":{
                "binder.brokers":"PLAINTEXT://kafka:9092",
                "streams.binder.brokers":"PLAINTEXT://kafka:9092",
                "binder.zkNodes":"zookeeper:2181",
                "streams.binder.zkNodes":"zookeeper:2181"
             },
             "task.management.metrics.export.influx":{
                "enabled":true,
                "db":"myinfluxdb",
                "uri":"http://influxdb:8086"
             },
             "stream.management.metrics.export.influx":{
                "enabled":true,
                "db":"myinfluxdb",
                "uri":"http://influxdb:8086"
             }
          },
          "spring.cloud.dataflow.grafana-info.url":"http://localhost:3000"
        }

  influxdb:
    image: influxdb:1.7.7
    container_name: influxdb
    ports:
      - '8086:8086'

  grafana:
    image: springcloud/spring-cloud-dataflow-grafana-influxdb:${DATAFLOW_VERSION:?DATAFLOW_VERSION is not set!}
    container_name: grafana
    ports:
      - '3000:3000'

