version: '3'

# Extends the default docker-compose.yml by mounting a host folder to the dataflow-server adn skipper containers.
# Usage: docker-compose -f ./docker-compose.yml -f ./docker-compose-mount-host-folder.yml up
#
# The HOST_MOUNT_PATH and DOCKER_MOUNT_PATH are used to set the host and docker mount folders.
# If not set HOST_MOUNT_PATH defaults to the local host folder where the docker compose is being started.
# If not set DOCKER_MOUNT_PATH defaults to /root/scdf on dataflow-server and skipper containers.
#
# For example to mount the local Maven repository to docker path /root/apps on Linux/MacOS:
#  HOST_MOUNT_PATH=~/.m2/repository/ DOCKER_MOUNT_PATH=/root/apps  docker-compose -f ./docker-compose.yml -f ./docker-compose-mount-host-folder.yml up
#
# Tips for different OS platforms:
#  - Linux/MacOS: export HOST_MOUNT_PATH=<your host folder> (e.g. export HOST_MOUNT_PATH=/tmp/myfolder)
#  - Windows Command Prompt: set HOST_MOUNT_PATH=<you host folder> (e.g. set HOST_MOUNT_PATH=C:\Users\User\MyDir)
#  - Windows PowerShell: $Env:HOST_MOUNT_PATH=="<you host folder>" (e.g. $Env:HOST_MOUNT_PATH="C:\Users\User\MyDir)
#
#  Tip: on Windows you can use the COMPOSE_CONVERT_WINDOWS_PATHS=1 to switch to linux like paths (e.g. https://docs.docker.com/compose/reference/envvars/)
services:
  dataflow-server:
    volumes:
      - ${HOST_MOUNT_PATH:-.}:${DOCKER_MOUNT_PATH:-/root/scdf}

  skipper-server:
    volumes:
      - ${HOST_MOUNT_PATH:-.}:${DOCKER_MOUNT_PATH:-/root/scdf}
