scdf:
  binder:
    type: rabbit
  server:
    service:
      type: LoadBalancer
    database:
      url: jdbc:$DATABASE://${DATABASE_HOST}/dataflow
      driverClassName: org.postgresql.Driver
      secretName: postgresql
      secretUsernameKey: database-username
      secretPasswordKey: database-password
    env:
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_STREAMS_ENABLED
        value: "true"
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_TASKS_ENABLED
        value: "true"
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
        value: "true"
  skipper:
    database:
      url: jdbc:$DATABASE://${DATABASE_HOST}/dataflow
      driverClassName: org.postgresql.Driver
      secretName: postgresql
      secretUsernameKey: database-username
      secretPasswordKey: database-password
  registry:
    secret:
      ref: "reg-creds-dev-registry"
