version: '3'

# Extends the default docker-compose.yml with Zipkin Server distributed tracing configuration.
# Usage: docker-compose -f ./docker-compose.yml -f ./docker-compose-zipkin.yml up

services:

  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin-server
    expose:
      - '9411'
    ports:
      - '9411:9411'

  dataflow-server:
    environment:
      - SPRING_CLOUD_DATAFLOW_APPLICATIONPROPERTIES_STREAM_MANAGEMENT_TRACING_ENABLED=true
      - SPRING_CLOUD_DATAFLOW_APPLICATIONPROPERTIES_STREAM_MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - SPRING_CLOUD_DATAFLOW_APPLICATIONPROPERTIES_STREAM_MANAGEMENT_ZIPKIN_TRACING_EXPORT_ENABLED=true
      - SPRING_CLOUD_DATAFLOW_APPLICATIONPROPERTIES_STREAM_MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
