version: '3'

# Reconfigures the default docker-compose.yml to replace Kafka/Zookeeper by RabbitMQ
# Usage: docker-compose -f ./docker-compose.yml -f ./docker-compose-rabbitmq.yml up
services:

  kafka-broker:
    entrypoint: ["echo", "kafka-broker service is disabled"]

  zookeeper:
    entrypoint: ["echo", "zookeeper service is disabled"]

  rabbitmq:
    image: rabbitmq:3.7
    container_name: dataflow-rabbitmq
    expose:
      - '5672'

  dataflow-server:
    environment:
      - SPRING_CLOUD_DATAFLOW_APPLICATIONPROPERTIES_STREAM_SPRING_RABBITMQ_HOST=rabbitmq

  app-import-stream:
    command: >
      /bin/sh -c "
        ./wait-for-it.sh -t 360 dataflow-server:9393;
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=${STREAM_APPS_URI:-https://dataflow.spring.io/rabbitmq-maven-latest&force=true}';
        wget -qO- 'http://dataflow-server:9393/apps/sink/ver-log/3.0.1' --post-data='uri=maven://org.springframework.cloud.stream.app:log-sink-kafka:3.0.1';
        wget -qO- 'http://dataflow-server:9393/apps/sink/ver-log/2.1.5.RELEASE' --post-data='uri=maven://org.springframework.cloud.stream.app:log-sink-kafka:2.1.5.RELEASE';
        echo 'Stream apps imported'"

