#@ load("mariadb.lib.yml", "name")
#@ load("mariadb.lib.yml", "username")
#@ load("mariadb.lib.yml", "password")

apiVersion: v1
kind: Secret
metadata:
  name: #@ name()
  labels:
    app: #@ name()
data:
  mariadb-root-password: #@ password()
  mariadb-user: #@ username()
  mariadb-password: #@ password()
