#@ load("mariadb.lib.yml", "name")
#@ load("mariadb.lib.yml", "username")
#@ load("mariadb.lib.yml", "password")
#@ load("mariadb.star", "image")
#@ load("mariadb.star", "has_image_pull_secrets")
#@ load("mariadb.star", "image_pull_secrets")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      containers:
      - image: #@ image()
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: #@ name()
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              key: mariadb-user
              name: #@ name()
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-password
              name: #@ name()
        - name: MARIADB_DATABASE
          value: #@ name()
        ports:
        - containerPort: 3306
          name: #@ name()
        volumeMounts:
        - name: data
          mountPath: /var/lib/mariadb
        args:
        - "--ignore-db-dir=lost+found"
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_unicode_ci"
      #@ if has_image_pull_secrets():
      imagePullSecrets: #@ image_pull_secrets()
      #@ else:
      imagePullSecrets: [{name: reg-creds}]
      #@ end
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: #@ name()
