management:
  metrics:
    tags:
      # Common SCDF stream app tags.
      stream.name: ${spring.cloud.dataflow.stream.name:unknown}
      application.name: ${spring.cloud.dataflow.stream.app.label:unknown}
      application.type: ${spring.cloud.dataflow.stream.app.type:unknown}
      instance.index: ${spring.cloud.stream.instanceIndex:0}
      application.guid: ${spring.cloud.application.guid:unknown}

      # Tags required to use the Wavefront Spring Boot tile.
      application: ${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}
      service: "stream application"
