#@ load("grafana.lib.yml", "name")
#@ load("grafana.lib.yml", "grafana_image")
#@ load("grafana.star", "has_image_pull_secrets")
#@ load("grafana.star", "image_pull_secrets")

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #@ name()
  name: #@ name()
spec:
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      containers:
        - image: #@ grafana_image()
          name: grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana
                  key: admin-username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana
                  key: admin-password
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 2500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/provisioning/datasources/datasources.yaml"
              subPath: datasources.yaml
      #@ if has_image_pull_secrets():
      imagePullSecrets: #@ image_pull_secrets()
      #@ else:
      imagePullSecrets: [{name: reg-creds}]
      #@ end
      volumes:
        - name: config
          configMap:
            name: grafana
