#@ load("prometheus-rsocket-proxy.lib.yml", "name")
#@ load("prometheus-rsocket-proxy.lib.yml", "prometheus_rsocket_proxy_image")
#@ load("prometheus-rsocket-proxy.star", "has_image_pull_secrets")
#@ load("prometheus-rsocket-proxy.star", "image_pull_secrets")

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #@ name()
  name: #@ name()
spec:
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      serviceAccountName: #@ name()
      containers:
        - name: #@ name()
          image: #@ prometheus_rsocket_proxy_image()
          ports:
            - name: scrape
              containerPort: 8080
            - name: rsocket
              containerPort: 7001
          resources:
            limits:
              cpu: 1.0
              memory: 2048Mi
            requests:
              cpu: 0.5
              memory: 1024Mi
      #@ if has_image_pull_secrets():
      imagePullSecrets: #@ image_pull_secrets()
      #@ else:
      imagePullSecrets: [{name: reg-creds}]
      #@ end
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
