#@ load("prometheus.lib.yml", "name")
#@ load("prometheus.lib.yml", "prometheus_image")
#@ load("prometheus.star", "has_image_pull_secrets")
#@ load("prometheus.star", "image_pull_secrets")

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #@ name()
  name: #@ name()
spec:
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: #@ prometheus_image()
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"
          ports:
            - name: prometheus
              containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      #@ if has_image_pull_secrets():
      imagePullSecrets: #@ image_pull_secrets()
      #@ else:
      imagePullSecrets: [{name: reg-creds}]
      #@ end
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus
        - name: prometheus-storage-volume
          emptyDir: {}
