apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-rsocket-proxy
  labels:
    app: prometheus-rsocket-proxy
subjects:
  - kind: ServiceAccount
    name: prometheus-rsocket-proxy
    namespace: prometheus
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
