name: Carvel Worker

on:
  workflow_dispatch:
    inputs:
      build-zoo-handler:
        description: 'Build Zoo Handler Payload'
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # zoo extract and ensure
    - name: Extract Zoo Context Properties
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-extract-context-properties: true
        ensure-env: |
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_version
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_version_nopostfix
          BUILD_ZOO_HANDLER_spring_cloud_dataflow_prerelease
          BUILD_ZOO_HANDLER_spring_cloud_skipper_version

    # Builds a package bundle
    - name: Build Package Bundle
      id: build-package-bundle
      uses: ./.github/actions/build-package-bundle
      with:
        dataflow-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
        skipper-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_skipper_version }}
        server-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
        server-repository: springcloud/spring-cloud-dataflow-server
        ctr-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
        package-name: scdf
        package-bundle-template: src/carvel/templates/bundle/package
        imgpkg-lock-template: src/carvel/templates/imgpkg
        config: src/carvel/config
        token: ${{ secrets.GITHUB_TOKEN }}

    # Publishes scdf package bundle as it needs to be in place
    # before repository bundle can be created.
    - name: Publish Package Bundle
      id: publish-package-bundle
      uses: ./.github/actions/publish-bundle
      with:
        path: ${{ steps.build-package-bundle.outputs.bundle-path }}
        repository: springcloud/scdf-package
        version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version_nopostfix }}
        prerelease: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_prerelease }}

    # Builds a repository bundle
    - name: Build Repository Bundle
      id: build-repository-bundle
      uses: ./.github/actions/build-repository-bundle
      with:
        version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
        repo-bundle-template: src/carvel/templates/bundle/repo
        package-bundle-repository: springcloud/scdf-package
        package-name: scdf
        token: ${{ secrets.GITHUB_TOKEN }}

    # Publishes scdf repo bundle
    - name: Publish Repository Bundle
      id: publish-repository-bundle
      uses: ./.github/actions/publish-bundle
      with:
        path: ${{ steps.build-repository-bundle.outputs.bundle-path }}
        repository: springcloud/scdf-repo
        version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version_nopostfix }}
        prerelease: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_prerelease }}

    # zoo success
    - name: Notify Build Success Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
        dispatch-handler-client-payload-data: >
          {
            "event": "carvel-succeed"
          }

    # zoo failure
    - name: Notify Build Failure Zoo Handler Controller
      if: ${{ failure() }}
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
        dispatch-handler-client-payload-data: >
          {
            "event": "carvel-failed"
          }
