name: CI IT Database

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  integration-test:
    name: DB IT on ${{ matrix.group }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [mariadb, postgres]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'liberica'
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.8.8
        maven-mirror: 'https://dlcdn.apache.org/maven/maven-3/'
    - name: Login dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: 'Action: Run Db IT'
      run: |
        mvn clean install -DskipTests -T 1C -s .settings.xml -pl spring-cloud-dataflow-server -am  
        mvn \
          -s .settings.xml \
          -pl spring-cloud-dataflow-server \
          -Dgroups=${{ matrix.group }} \
          -Pfailsafe \
          --batch-mode \
          test
    - name: Integration Test Report for ${{ matrix.group }}
      id: test_report
      uses: dorny/test-reporter@v1
      if: ${{ success() || failure() }}
      with:
        name: Integration Tests - ${{ matrix.group }}
        path: '**/surefire-reports/*.xml'
        reporter: java-junit
        list-tests: failed
    - name: Publish Test Url for ${{ matrix.group }}
      shell: bash
      run: |
        echo "::info ::Test report for ${{ matrix.group }} published at ${{ steps.test_report.outputs.url_html }}"
    - name: 'Action: Upload Unit Test Results'
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.group }}-test-results-surefire
        path: './**/target/surefire-reports/**/*.*'
        retention-days: 7
        if-no-files-found: ignore
    - name: 'Action: Upload Integration Test Results'
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.group }}-test-results-failsafe
        path: './**/target/failsafe-reports/**/*.*'
        retention-days: 7
        if-no-files-found: ignore
  db2-tests:
    name: DB2 Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'
      - uses: jvalkeal/setup-maven@v1
        with:
          maven-version: 3.8.8
          maven-mirror: 'https://dlcdn.apache.org/maven/maven-3/'
      - name: Login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Action: Run DB2 Tests'
        env:
          ENABLE_DB2: 'true'
        run: |
          mvn clean install -DskipTests -T 1C -s .settings.xml -pl :spring-cloud-dataflow-server,:spring-cloud-skipper-server -am  
          mvn \
            -s .settings.xml \
            -pl :spring-cloud-dataflow-server,:spring-cloud-skipper-server \
            -Dgroups=DB2 \
            --batch-mode \
            test
      - name: Test Report for DB2
        id: test_report
        uses: dorny/test-reporter@v1
        if: ${{ success() || failure() }}
        with:
          name: Tests - DB2
          path: '**/surefire-reports/*.xml'
          reporter: java-junit
          list-tests: failed
      - name: Publish Test Url for DB2
        shell: bash
        run: |
          echo "::info ::Test report for DB2 published at ${{ steps.test_report.outputs.url_html }}"
      - name: 'Action: Upload Unit Test Results'
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: DB2-test-results-surefire
          path: './**/target/surefire-reports/**/*.*'
          retention-days: 7
          if-no-files-found: ignore
  completed:
    runs-on: ubuntu-latest
    needs: [ db2-test, integration-test ]
    steps:
      - name: 'Done'
        shell: bash
        run: echo "::info ::Done"
