name: CI IT Database

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    name: DB IT on ${{ matrix.group }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
#        group: [mariadb, mssql, postgres] // let's move mssql to pro tests along with Oracle
        group: [mariadb, postgres]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - name: Run Db IT
      run: |
        mvn \
          -s .settings.xml \
          -pl spring-cloud-dataflow-server \
          -Dgroups=${{ matrix.group }} \
          -Pfailsafe \
          --batch-mode \
          integration-test \
          verify
