name: CI PRs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'liberica'
    - name: Build
      shell: bash
      timeout-minutes: 75
      run: |
        ./mvnw -B -s .github/settings.xml -Pdocs clean install
