name: CI PRs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        dotnet: false
        docker-images: false
        swap-storage: false
        large-packages: false
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'liberica'
    - name: Build
      shell: bash
      timeout-minutes: 75
      run: |
        ./mvnw -B -s .github/settings.xml clean install
    - name: Capture Test Results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Unit Tests
        path: '**/surefire-reports/*.xml'
        retention-days: 3
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
      - name: 'Scanned'
        shell: bash
        run: echo "::info ::Scanned"
  done:
    runs-on: ubuntu-latest
    needs: [ scan, build ]
    steps:
      - name: 'Done'
        shell: bash
        run: echo "::info ::Done"
